### ISSUE TITLE
Catch 'Corrupt JPG, exceeded buffer limits'

### ISSUE THREAD

**Issue by felipelvira** [image-size/image-size#70] opened 2016-03-15 23:03 UTC
Hi, 
Currently i'm developing a node js application to upload files to AWS.
I'm using a buffer to get the width and height of an image using `sizeOf(file.buffer)`. Some files may be corrupted or damaged, for this scenario  i want to set the height and width to zero. 

How can i catch the `TypeError` before my application fail?
Thanks.

**Comment by apocist** [comment] 2016-04-07 22:50
I have used a try catch to success catch the error before continuing:
```
var sizeOf = require('image-size');
try {
var dimensions = sizeOf(file.path);
}
catch(e){
that.logError(file.filename+":"+ e.message);
}
```

This may be a duplicate of #37

**Comment by netroy** [comment] 2017-07-19 12:59
I've temporarily increased the buffer size.. that should fix the issue for most users..
I'm gonna [rework the code to use streams instead of a fixed length buffer](https://github.com/image-size/image-size/issues/94).

**Closed by netroy** 2017-07-19 12:59 UTC
