### ISSUE TITLE
Avif support

### ISSUE THREAD

**Issue by cachila** [image-size/image-size#348] opened 2020-11-09 21:22 UTC
Hi,

Are you planning to support AVIF format? I would love to use the tool but I need that support.

Thanks

**Comment by netroy** [comment] 2020-11-10 10:53
marking this as a duplicate of #125, as AVIF is HEIF files with AV1 compression instead of HEVC.
Since this module does not deal with actual pixel data, all HEIF formats will be supported when #125 is closed.

**Closed by netroy** 2020-11-10 10:53 UTC

**Comment by netroy** [comment] 2023-12-28 16:38
released in v1.1.0
