### ISSUE TITLE
HEIC Files

### ISSUE THREAD

**Issue by emmtte** [image-size/image-size#247] opened 2019-11-09 17:10 UTC
Do you know if this repo support HEIC photo file

**Comment by netroy** [comment] 2019-11-09 18:33
Hey @ManuCart, 
HEIC containers aren't supported yet.
as there hasn't been any demand for it so far.

If you have some time to add support, give it a shot. 
If not, I can try sometime next week to start with it. 

Cheers :)

**Comment by ManuCart** [comment] 2019-11-10 11:05
I don't have the background to do this.
I will wait. Thanks for your help

**Comment by netroy** [comment] 2020-11-10 10:49
duplicate of #125

**Closed by netroy** 2020-11-10 10:49 UTC

**Comment by netroy** [comment] 2023-12-28 16:38
released in v1.1.0
